name: Test & Build Maven Project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Run main class (dry run)
        run: mvn exec:java

      - name: Run tests
        run: mvn test

      - name: Build JAR
        run: mvn package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: ecommerce-app
          path: target/*.jar
