name: Test & Build Maven Project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Run main class (dry run)
      working-directory: ./ecommerce-mockito
      run: mvn exec:java

    - name: Run tests
      working-directory: ./ecommerce-mockito
      run: mvn test
