name: Java CI z Maven i Super-Linter

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Skonfiguruj JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Testowe uruchomienie aplikacji
        run: mvn exec:java -Dexec.mainClass="ecommerce.model.Main" --batch-mode

      - name: Lintowanie kodu
        uses: super-linter/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVA: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: .*\.(java)$
          DEFAULT_BRANCH: main

      - name: Uruchom testy jednostkowe
        run: mvn test --batch-mode

      - name: Spakuj aplikację
        run: mvn package --batch-mode

      - name: Prześlij artefakt JAR
        uses: actions/upload-artifact@v4
        with:
          name: ecommerce-jar
          path: target/*.jar
          retention-days: 7
